### PR TITLE
Update reset-password.html

### PR DESCRIPTION
**Pull request by kasinico**
back button

### CODE REVIEW

**Comment by kasinico** [comment]
<input
                value="Cancel"
                type="button"
                onclick="location.href='{% url "index" %}';">

**Comment by kallyas** [comment]
@kasinico you closed this PR, you nolonger proposing changes?

**Comment by kasinico** [comment]
Yea will first make some changes of Back button (to login page) on local

**Comment by kallyas** [comment]
okay

**Pull request closed without merging**
